### ISSUE TITLE
Error, module not found

### ISSUE THREAD

**Issue by alexgleith** [sudhirkshirsagar/cawildfires#1]
>Module not found: Error: Can't resolve './aws-exports' in '/Users/alex/git/misc/cawildfires/src'

This error occurs when you run the app and there's no docs on what is expected for this module.

**Comment by sudhirkshirsagar** [comment]
Thanks for your interest. You need to install AWS Amplify Geo libraries. 
Here is some info. https://aws.amazon.com/blogs/mobile/add-maps-to-your-app-in-3-steps-with-aws-amplify-geo/
Our app has been published to https://prod.d2jk958qdk2lhm.amplifyapp.com/
